//! Tool catalog — one command answering "what tools exist, what does each
//! do, how to invoke" (DDL-91a).
//!
//! Reads exclusively from the ONE registry (`MANAGED_TOOLS`); there is no
//! second, richer source of truth. The same rendering feeds both the CLI
//! output and the generated `docs/capability-matrix.md`, which is kept
//! honest by the drift test in `tests/tool_registry_drift.rs`.

use crate::platform::{MANAGED_TOOLS, Tool};
use serde::Serialize;

/// One catalog row: tool identity, invoked binary, and one-line purpose.
#[derive(Debug, Clone, Serialize)]
pub struct CatalogEntry {
    pub name: &'static str,
    /// Command to invoke once installed. Equals the registry name; kept as
    /// an explicit field so consumers never guess binary-from-crate.
    pub binary: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub maturity: &'static str,
    pub repo: &'static str,
}

/// Catalog entries for every managed tool, in registry order.
pub fn entries() -> Vec<CatalogEntry> {
    MANAGED_TOOLS
        .iter()
        .map(|t| CatalogEntry {
            name: t.name,
            binary: binary_name(t),
            description: t.description,
            category: t.category.as_str(),
            maturity: t.maturity.as_str(),
            repo: t.repo,
        })
        .collect()
}

/// The command users invoke for a tool. Every managed tool's binary equals
/// its registry name (bd ships `bd`, wai ships `wai`, ...).
fn binary_name(tool: &Tool) -> &'static str {
    tool.name
}

/// Human-readable catalog table (sorted by category tier, then name).
pub fn render_human() -> String {
    let mut out = String::new();
    out.push_str("dulce-de-leche — tool catalog\n");
    out.push('\n');
    for (tier, heading) in [
        ("core", "Core"),
        ("recommended", "Recommended"),
        ("extension", "Extension"),
    ] {
        let all = entries();
        let mut tools: Vec<&CatalogEntry> = all.iter().filter(|e| e.category == tier).collect();
        tools.sort_by(|a, b| a.name.cmp(b.name));
        out.push_str(&format!("{heading}:\n"));
        for entry in tools {
            out.push_str(&format!(
                "  {:<12} {}\n    {}\n",
                entry.name, entry.repo, entry.description
            ));
        }
        out.push('\n');
    }
    out.push_str("Install any of these with `ddl install <name>`.\n");
    out
}

/// Generate `docs/capability-matrix.md` from the registry. Committed to the
/// repo and drift-checked by `capability_matrix_matches_generation`.
pub fn render_capability_matrix() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by src/catalog.rs (render_capability_matrix) — DO NOT HAND-EDIT. -->\n",
    );
    out.push_str("# Capability matrix\n\n");
    out.push_str(
        "Intent → tool mapping for the charly-vibes ecosystem, generated from \
         ddl's tool registry. For the narrative behind each tool, see \
         [ecosystem-map.md](ecosystem-map.md).\n\n",
    );
    out.push_str("| Tool | Binary | Purpose | Category | Maturity |\n");
    out.push_str("|------|--------|---------|----------|----------|\n");
    for entry in entries() {
        out.push_str(&format!(
            "| {} | `{}` | {} | {} | {} |\n",
            entry.name, entry.binary, entry.description, entry.category, entry.maturity
        ));
    }
    out.push_str(&format!(
        "\nInstall any of these with `ddl install <name>` — {} tools total.\n",
        entries().len()
    ));
    out
}
